### ISSUE TITLE
Create and element for text-view

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#194]
Create an element to test the text-view based on the latest refractored code.

**Comment by sebastian-nehrdich** [comment]
I have this now to 70% working, I am confident that I can push the working text-view within the next few days. The current code is however still nothing that can be called 'nice to read' and requires some serious refactoring in the long run. I have done some right now but that is just as much as I can do in the limited amount of time.

**Comment by sebastian-nehrdich** [comment]
Currently the text-view suffers from a major performance issue. 
It can be reproduced by calling one of the larger files:
https://buddhanexus.net/tib/text/T06TD4035E
It takes ages until the entire dom is rendered. In the performance monitor, most of the time of the rendering is used up by 'recalculate styles'. 
the problem can be entirely solved by moving calling <text-view-left> element not from within text-view.js but directly from within data-view.js. In that case, instead of taking 10-20 seconds the entire site is rendered in less then two seconds. 
What I tried so far to solve this problem:
- remove all kind of event handlers
- use shouldUpdate both within text-view.js and text-view-left.js so that updates are only run when the fileName has changed and nothing else 
- render directly into the dom without using the shadow DOM

I suspect that the problem can be solved by changing the subelements of <text-view> into normal functions and calling them from within text-view, but I don't think we should to go that route...
a few observations:
- reducing the numbers of span elements in the text-view-left.js rendering has a great effect on the speed (the less, the faster)
- removing inline styles from the templates did not help so far
- it *might* be related to the depth of the dom at this point. I have the impression that for some hard-to-grasp reason, the dom with the rendered result is getting moved around a couple of times within the trees, things get deleted and created again...

**Comment by sebastian-nehrdich** [comment]
It just struck me like a lightning during meditation yesterday that we just shouldn't do it like this. 
When I tested a bit more yesterday I figured out that the newest chrome-version has problems to render large files in the old json-based version of the website. I think it is safe to conclude that because of the large size of the DOM (15,000 span elements or even more), all the webbrowsers run into some kind of trouble, they just deal with it slightly different. 
My  idea now is to just render what is in the viewport + use infinitive scrolling on the left text. So we only need to query for a few dozen segments and render them. This solves the problem entirely but introduces a new problem: The search function of the webbrowser is not helpful anymore to find any position in the text. This again can be solved by adding a simple search function that only searches through the segments of the left text and not more. In the worst case, this will be 10,000-20,000 segments. I will try and implement a query on the backend and see how the performance is going to be. I do not think we will run into trouble here.
Same goes for the text-view-right: Just render what is in the viewport and add infinitive scrollin in both directions, so there really is no problem. Should also save us a lot of traffic...

**Comment by sebastian-nehrdich** [comment]
let's consider the changes proposed in my last comment here as done. The search function might deserve a seperate issue, also because that feature might be integrated in the table-view as well. 
I have also integrated the 'move to left column' functionality today. It's a bit more fancy compared to what we did before. It now scrolls precisely to the position that was selected on the right text and selects the related words. I think this is a bit more convenient this way, but if you have a different impression please let me know!
