### ISSUE TITLE
Spinning Dharma wheel not working when scrolling in the table view

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus-frontend#201]
Currently, when scrolling the table-view, the spinning dharma wheel does not show as expected when the endless scrolling reload is trigget at the end of the table.

**Comment by ayya-vimala** [comment]
Can you give an example where this happens because when I try to load any text, and put a few console.logs on, it tells me that `this.fetchLoading` indeed becomes true every time the next page of the scrolling is triggered and it indeed renders the spinner. But it seems to go so fast that it does not have time to really show itself.

**Comment by ayya-vimala** [comment]
![image](https://user-images.githubusercontent.com/49606945/88020017-387d7600-cb2b-11ea-941e-062f16d8d9f2.png)

**Comment by sebastian-nehrdich** [comment]
it seems to set the flag correctly, yes. But I don't think it goes so fast that it becomes invisible. For example on https://buddhanexus2.kc-tbts.uni-hamburg.de/tib/table/T06D4035 the fetching of new parallels when scrolling down takes quite a while and there is no spinning wheel.
I rather suspect that the position of the spinning wheel is too far to the top and it is therefore out of focus and not visible. I'll look into this...

**Comment by ayya-vimala** [comment]
I had set the console.log on LoadingSpinner.js just before the actual image inside the RENDER function.

**Comment by ayya-vimala** [comment]
I think I know what the issue is: it is most likely the z-index of the spinning wheel. In other words: it is there but underneath the parallels.
