### ISSUE TITLE
Performance for table view

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#26]
The performance of the table view has become a bit slow, also for smaller files.

**Comment by sebastian-nehrdich** [comment]
One reason for that is also related to the rendering on the frontend.
tokenizeWords is wrapping each word (in Chinese, each character!) into it's
own span-tag and that adds significantly to the rendering time.
This can be solved by writing an alternative version of tokenizeWords for
the table-view, since such a fine level of differentiation is not needed
there. it's only relevant for the text-view.
It's something I want to do at _some_ time in the future when nothing else
is pressing. :D
