### ISSUE TITLE
Text View performance issues because of complex rendering

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus-frontend#63]
On the text display, each character in Chinese or each word in Tibetan/Pali is wrapped into a span element and gets a position attribute. In this way when clicking on a word, we know which parallels we have to fetch from the database for the middle view.
However this method is expensive and slows down the rendering of text. In the case of Sanskrit, this will be especially problematic because we might have to wrap each single letter into a span because word-boundaries are often inside compounds etc. and we would quickly end up with thousands of span elements even for a short piece of text. 
I wonder: Is there maybe a way in Javascript to figure out at which position of the text the mouse courser was during click without resorting to span elements? In that way we could drastically reduce the amount of tags that need to be rendered!

**Comment by TrebuhD** [comment]
I'll have to take a deeper look, but at first glance, I suspect the number of spans might not be the problem here. [Here ](https://buddhanexus.net/tib/text/K01acip-k_lha_sa-001-001) for example, the left view has only around ~2100 spans (which is not a really big amount), but it still stutters on my modern Ryzen 3600 CPU.

I didn't dive in the code yet, but could the issue be excessive scroll listeners or some render-blocking task performed after each scroll? If there's a method called on every scroll, try to wrap that method inside `requestAnimationFrame`. https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame.

If you want, as a refactor, you can also try componentizing the word / character element (preferably extending the LightDOM base component, since there's a lot of these and we don't want to create many shadow DOM roots). Then, every word / character would have an `@onClick` listener, which would remove the need to manually query the DOM for the `position` attribute.

**Comment by sebastian-nehrdich** [comment]
thank you for this, it is very valuable input! Yes I was thinking also that having a few thousand spans *should* not be a big problem. I'll have a look into your suggestions this afternoon.

**Comment by ayya-vimala** [comment]
One thing to look out for here is that after a limit filter is applied of which the result is that there are no matches/parallels on the current page, the highlighting does not adjust to show this: it remains highlighted and it looks as if there are parallels.
